export default {
    es:{
        PORTFOLIO:'Portafolio',
        HOME: "Casa",
        ABOUTME: "Sobre mi",
        EXPERIENCE: "Experencia", 
        PROJECTS :"Proyectos", 
        CONTACT: "Contacto",
        BIRTHDAY:"Fecha de nacimiento",
        ABOUTMETEXT:"Soy un estudiante que actualmente estudia Desarrollo de Aplicaciones Web. A lo largo de mi carrera he aprendido a configurar y operar sistemas informáticos, adaptando sus configuraciones según sea necesario. También he adquirido experiencia en la aplicación de técnicas y procedimientos de seguridad relacionados a sistemas, servicios y aplicaciones. Además, puedo administrar servidores de aplicaciones, ajustar sus configuraciones y administrar bases de datos interpretando su diseño lógico y verificando su integridad y consistencia. También soy capaz de desarrollar aplicaciones con acceso a bases de datos utilizando varios lenguajes de programación. Además, he desarrollado fuertes habilidades de trabajo en equipo a través de la colaboración en varios proyectos.",
        AGE:"Edad",
        RESIDENCE:"Residencia",
        SPAIN: 'Espana',
        ADDRESS: 'Direccion',
        PHONE:'Telefono',
        FULLNAME: 'Nombre Completo',
        MESSAGE: 'Mensaje',
        SUBMIT: 'Mandar',
        SKILL: 'Habilidades',
       
    },
    en:{
        PORTFOLIO:'Portfolio',
        HOME: "Home",
        ABOUTME: "About me",
        EXPERIENCE: "Experience",
        PROJECTS : "Projects",
        CONTACT: "Contact",
        BIRTHDAY:"Birthday",
        ABOUTMETEXT:"I am a student currently studying Web Application Development. Throughout my course, I have learned how to congure and operate computer systems, adapting their congurations as needed. I have also gained experience inapplying security techniques and procedures related to systems, services, and applications. Additionally, I can manageapplication servers, adjust their congurations, and manage databases by interpreting their logical design and verifyingintegrity and consistency. I am also capable of developing applications with database access using variousprogramming languages. Moreover, I have developed strong teamwork skills through collaboration on various projects"  ,      
        AGE:"Age",
        RESIDENCE:"Residence",
        SPAIN: 'Spain',
        ADDRESS: 'Address',
        PHONE:'Phone',
        FULLNAME: 'Full Name',
        MESSAGE: 'Message',
        SUBMIT: 'Submit',
        SKILL: 'Skills',
    }
}